### ISSUE TITLE
数据库可以用 Workers KV 吗

### ISSUE THREAD

**Issue by gitiray** [snakeying/GPT-Telegram-Worker#1]
这样就能全套部署在 CF 了，而不是其它第三方有用量限制

**Comment by snakeying** [comment]
可以使用kv，但免费用户kv读写每天只有1000次，upstash每天提供10k。考虑到大量读写情况才决定调用upstash

**Comment by gitiray** [comment]
这样啊，那除了这个upstash还可以用其它替代吗？10k如果用得多可能也有点不够

**Comment by snakeying** [comment]
目前暂时没有发现。。。
