### ISSUE TITLE
使用/flux图像生成后，redis之前存储的context会被清空

### ISSUE THREAD

**Issue by xysele** [snakeying/GPT-Telegram-Worker#2]
使用/flux图像生成后，redis之前存储的context会被清空

**Comment by snakeying** [comment]
我尝试多次，均未能重现你的bug。请仔细检查配置，如果还有出现，请告诉我
![1](https://github.com/user-attachments/assets/e68ad686-f349-41cb-93c0-c08b43a1884a)

**Comment by xysele** [comment]
不是bug，应该是我重新对话导致的
