### ISSUE TITLE
对话复用的疑问

### ISSUE THREAD

**Issue by gitiray** [snakeying/GPT-Telegram-Worker#3]
目前是否只有通过 /new 命令或者切换了模型，才会启用一个新的对话？
如果只是发送消息而不 /new，是一直在同一个对话里？

如果是，可否考虑改成：
通过回复消息的方式发送内容给bot时才关联复用在一个对话里
否则直接发送就是新会话

**Comment by snakeying** [comment]
目前只有通过 /new 命令或者/switchmodel命令切换模型，才会启用一个新的对话（有提示）

我不太明白你的建议？

**Comment by gitiray** [comment]
![图片](https://github.com/user-attachments/assets/365504cd-1260-4b93-b2d5-746d34bc255b)

我的想法是像这样，第一个标记的内容是直接发送的，就是新对话
第二个标记是对某条消息回复的形式，就会复用对应的对话

**Comment by snakeying** [comment]
暂时没有打算改成这种交互方式，因为
1. 不太符合大部分人的交互习惯
2. 如果改成这样，每次用户发送信息时，token计算将增加，比如原本上下文只是
用户：你好
AI：你好！很高兴见到你。你想聊些什么呢？
用户：xxx
上下文只有
```
用户：你好
AI：你好！很高兴见到你。你想聊些什么呢？
```
再次交互也只会发送以上这些，如果按照你的想法改动，则变成发送两次
